table Fact_Sales
	lineageTag: 0d930313-57dd-46c6-959c-96639d4d94fd

	measure 'Total Sales' =
			
			SUM(Fact_Sales[sales_amount])
		lineageTag: 14f779ab-74b6-4c5c-bfd3-83df8dca8dbb

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'MoM Growth %' =
			
			VAR CurrentSales = [Total Sales]
			VAR PreviousSales =
			    CALCULATE(
			        [Total Sales],
			        DATEADD(Dim_Date[Date], -1, MONTH)
			    )
			RETURN
			DIVIDE(
			    CurrentSales - PreviousSales,
			    PreviousSales
			)
		lineageTag: 41423b84-de2a-4a83-9d31-b46601c2dae9

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Running Total Sales' =
			
			CALCULATE(
			    [Total Sales],
			    FILTER(
			        ALL(Dim_Date[Date]),
			        Dim_Date[Date] <= MAX(Dim_Date[Date])
			    )
			)
		lineageTag: 70a79138-245d-4f80-ade1-2265f959e07f

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Product Rank' =
			
			RANKX(
			    ALL(Dim_Product[item]),
			    [Total Sales],
			    ,
			    DESC,
			    DENSE
			)
		formatString: 0
		lineageTag: 5460bd67-b4bd-4d8d-af84-e6848a89c22a

	measure 'Average Transaction Value' =
			
			DIVIDE(
			    [Total Sales],
			    DISTINCTCOUNT(Fact_Sales[sale_id])
			)
		lineageTag: b4491e7c-e46f-449d-9619-6f295d7b5e6f

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column sale_id
		dataType: int64
		formatString: 0
		lineageTag: feb02aba-a8d7-4c6a-8148-3074cac48147
		summarizeBy: sum
		sourceColumn: sale_id

		annotation SummarizationSetBy = Automatic

	column date
		dataType: dateTime
		formatString: Long Date
		lineageTag: a6a1078d-4f6e-4e5e-8b26-da640c7e1c81
		summarizeBy: none
		sourceColumn: date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column city
		dataType: string
		lineageTag: 4dff27f8-5415-495c-9145-04afe8733d31
		summarizeBy: none
		sourceColumn: city

		annotation SummarizationSetBy = Automatic

	column store_format
		dataType: string
		lineageTag: c4ecbd4e-0410-4322-8832-94208fd87eb8
		summarizeBy: none
		sourceColumn: store_format

		annotation SummarizationSetBy = Automatic

	column category
		dataType: string
		lineageTag: 920b0221-a9a9-4324-9789-eb960db5c932
		summarizeBy: none
		sourceColumn: category

		annotation SummarizationSetBy = Automatic

	column item
		dataType: string
		lineageTag: 60baa08f-e22b-403a-93ba-e0b0fd9b8a42
		summarizeBy: none
		sourceColumn: item

		annotation SummarizationSetBy = Automatic

	column quantity
		dataType: int64
		formatString: 0
		lineageTag: 261bf8b3-a201-4276-9bca-d3672eb97439
		summarizeBy: sum
		sourceColumn: quantity

		annotation SummarizationSetBy = Automatic

	column unit_price
		dataType: int64
		formatString: 0
		lineageTag: d7d00267-5ad5-4aea-8be9-aa8fb9ccdde1
		summarizeBy: sum
		sourceColumn: unit_price

		annotation SummarizationSetBy = Automatic

	column sales_amount
		dataType: double
		lineageTag: 18a145f4-0556-452f-be62-89c0d456e6c7
		summarizeBy: sum
		sourceColumn: sales_amount

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition Fact_Sales = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("E:\Bussiness Intelligence\brewmetrics-bi\brewmetrics_sales.csv"),[Delimiter=",", Columns=9, Encoding=1252, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"sale_id", Int64.Type}, {"date", type date}, {"city", type text}, {"store_format", type text}, {"category", type text}, {"item", type text}, {"quantity", Int64.Type}, {"unit_price", Int64.Type}, {"sales_amount", type number}})
				in
				    #"Changed Type"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

